spring:
  application:
    name: "gateway-server"

  config:
    #  import: "optional:configserver:http://config-server:8071"
    import: "optional:configserver:http://localhost:8071/"

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

  cache:
    type: caffeine
    cache-names:
      - loadbalancer
    caffeine:
      spec: maximumSize=1000, expireAfterWrite=30s

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    gateway:
      access: unrestricted

  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Gateway Service"
    version: "1.0.0"

logging:
  level:
    com:
      app:
        gatewayserver: DEBUG