services:
  accounts:
    image: "uday510/accounts:latest"
    container_name: accounts-service
    hostname: accounts-service
    ports:
      - "${ACCOUNTS_PORT}:8080"
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
    deploy:
      resources:
        limits:
          memory: 512m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - micro-net

  loans:
    image: "uday510/loans:latest"
    container_name: loans-service
    hostname: loans-service
    depends_on:
      - accounts
    ports:
      - "${LOANS_PORT}:8090"
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
    deploy:
      resources:
        limits:
          memory: 512m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - micro-net

  cards:
    image: "uday510/cards:latest"
    container_name: cards-service
    hostname: cards-service
    depends_on:
      - accounts
    ports:
      - "${CARDS_PORT}:9000"
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
    deploy:
      resources:
        limits:
          memory: 512m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - micro-net

networks:
  micro-net:
    driver: bridge