server:
  port: 8090

spring:
  application:
    name: "loans"

  profiles:
    active: "default"

  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always 

  config:
    import: "configserver:http://localhost:8071"

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"