server:
  port: 9010

spring:
  application:
    name: "message-queue"
  cloud:
    function:
      definition: email|sms
    stream:
      bindings:
        emailsms-in-0:
          destination: send-communication
          group: ${spring.application.name}
        emailsms-out-0:
          destination: communication-sent
          group: ${spring.application.name}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s

logging:
  level:
    # Your application's base package - adjust to match your actual package
    com.app.accounts: DEBUG

    # HikariCP connection pool
    com.zaxxer.hikari: TRACE
    com.zaxxer.hikari.HikariConfig: DEBUG

    # Spring
    org.springframework.transaction: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG

    org.springframework.cloud.stream: DEBUG
    org.springframework.amqp.rabbit: DEBUG
    org.springframework.messaging: DEBUG

    # Root logger
    root: INFO

  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%thread]){blue} %clr(%-5level){green} %clr(%logger{36}){cyan} - %clr(%msg){white}%n"     