services:
  network-deploy-service:
    networks:
      - micro-net

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 512m
    environment:
      SPRING_RABBITMQ_HOST: "rabbitmq"

  microservice-configservice-config:
    extends:
      service: microservice-base-config
    depends_on:
      - configserver
      - eurekaserver 

    environment:
      SPRING_PROFILES_ACTIVE: qa
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka
