server:
  port: 8080

spring:
  application:
    name: "accounts"

  profiles:
    active: "prod"

  datasource:
    # For local development:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: root

    #     For Docker/production:
    # url: jdbc:mysql://accounts-db:3306/accountsdb
    # username: root
    # password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: CardsHikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      initialization-fail-timeout: 30000
      leak-detection-threshold: 60000
      auto-commit: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

  sql:
    init:
      mode: always # For dev; consider 'never' for production if DB is preloaded

  config:
    # For local dev:
    import: "configserver:http://localhost:8071"
    # For Docker/production:
    # import: "configserver:http://config-server:8071"

  rabbitmq:
    # For local dev:
    host: localhost
    # host: rabbitmq
    port: 5672
    username: guest
    password: guest
  
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      resilientServiceCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        slowCallRateThreshold: 30
        slowCallDurationThreshold: 2s
        eventConsumerBufferSize: 10
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
  retry:
    configs:
      default:
        max-attempts: 3
        waitDuration: 500
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        ignoreExceptions:
          - java.lang.NullPointerException
        retryExceptions:
          - java.util.concurrent.TimeoutException

resilience4j.ratelimiter:
  configs:
    default:
      timeoutDuration: 1000
      limit-refresh-period: 5000
      limitForPeriod: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      # For local dev:
      defaultZone: "http://localhost:8070/eureka"
      # For Docker/production:
      # defaultZone: "http://eureka-server:8070/eureka"

info:
  app:
    name: "accounts"
    description: "Accounts Service"
    version: "1.0.0"

logging:
  level:
    # Your application's base package - adjust to match your actual package
    com.app.accounts: DEBUG

    # HikariCP connection pool
    com.zaxxer.hikari: TRACE
    com.zaxxer.hikari.HikariConfig: DEBUG

    # Hibernate/JPA
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.stat: DEBUG
    org.hibernate.engine.jdbc.spi.SqlStatementLogger: DEBUG

    # Connection management
    org.hibernate.engine.jdbc.connections: DEBUG
    org.hibernate.orm.connections.pooling: DEBUG

    # Spring
    org.springframework.transaction: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG

    # Root logger
    root: INFO

  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%thread]){blue} %clr(%-5level){green} %clr(%logger{36}){cyan} - %clr(%msg){white}%n"