services:
  network-deploy-service:
    networks:
      - micro-net

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 512m
    environment:
      SPRING_RABBITMQ_HOST: "rabbitmq"

  microservice-configservice-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
