services:

  configserver:
    image: "uday510/config-server:latest"
    container_name: config-server
    platform: linux/arm64
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "uday510/eureka-server:latest"
    container_name: eureka-server
    platform: linux/arm64
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configservice-config

  accounts:
    image: "uday510/accounts:latest"
    container_name: accounts-service
    platform: linux/arm64
    hostname: accounts-service
    ports:
      - "8080:8080"
    depends_on:
      eurekaserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configservice-config

  cards:
    image: "uday510/cards:latest"
    container_name: cards-service
    platform: linux/arm64
    ports:
      - "9000:9000"
    depends_on:
      eurekaserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configservice-config

  loans:
    image: "uday510/loans:latest"
    container_name: loans-service
    platform: linux/arm64
    ports:
      - "8090:8090"
    depends_on:
      eurekaserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configservice-config

  gatewayserver:
    image: "uday510/gateway-server:latest"
    container_name: gateway-server
    platform: linux/arm64
    ports:
      - "8072:8072"
    depends_on:
      accounts:
        condition: service_healthy
      cards:
        condition: service_healthy
      loans:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8072/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configservice-config

networks:
  micro-network:
    external: true