services:
  auth-service:
    image: quay.io/keycloak/keycloak:26.2.5
    container_name: auth-server
    command: start-dev
    ports:
      - "7080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
#     networks:
#       - micro-network

# networks:
#   micro-network:
#     external: true