services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"     # Broker port
      - "15672:15672"   # Management UI
    networks:
      - micro-network
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics check_port_connectivity || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

networks:
  micro-network:
    external: true