spring:
  application:
    name: "eureka-server"

  config:
    # import: "optional:configserver:http://config-server:8071"
    import: "optional:configserver:http://localhost:8071"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true